version: "3.9"

services:
  # Our Postgres database
  db:
    ports:
      - 5433:5432

  # Adminer provides a nice little web UI to connect to databases
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
